ALTER TABLE rentals
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;

ALTER TABLE rentals
ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP;

ALTER TABLE rentals
ADD COLUMN IF NOT EXISTS terminated_at TIMESTAMP;

ALTER TABLE rentals
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

UPDATE rentals
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

ALTER TABLE rentals
ALTER COLUMN created_at SET NOT NULL;
